name: "UHPPOTE MQTT"
description: "UHPPOTE to MQTT bridge"
version: "0.0.4"
slug: "uhppote"
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - i386
image: "ghcr.io/wouterdebie/{arch}-uhppote-mqtt"
ports:
  60001/udp: 60001
schema:
  uhppote_device_id: int
  uhppote_device_ip: int
  bind: int
  name: str
  door: int
  mqtt_id: str
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: str
  base_topic: str
options:
  uhppote_device_id: null
  uhppote_device_ip: null
  bind: "0.0.0.0:60001"
  name: null
  door: 1
  mqtt_id: "uhppote-gate"
  mqtt_host: "homeassistant.local"
  mqtt_port: 1883
  mqtt_username: "homeassistant"
  mqtt_password: null
  base_topic: "homeassistant/lock/uhppote"

