name: "UHPPOTE MQTT"
description: "UHPPOTE to MQTT bridge"
version: "0.0.13"
slug: "uhppote"
init: false
arch:
  - aarch64
  - amd64
  - armv7
  - i386
image: "ghcr.io/wouterdebie/{arch}-uhppote-mqtt"
ports:
  60001/udp: 60001
schema:
  uhppote_device_id: int
  uhppote_device_ip: str
  bind: str
  name: str
  door: int
  mqtt_id: str
  base_topic: str
options:
  uhppote_device_id: null
  uhppote_device_ip: null
  bind: "0.0.0.0:60001"
  name: null
  door: 1
  mqtt_id: "uhppote-gate"
  base_topic: "homeassistant/lock/uhppote"
services:
  - mqtt:need
hassio_api: true
hassio_role: default
homeassistant_api: true
